## 类型的定义

In [1]:
import numpy as np

In [14]:
a1 = np.array([1,2,3,4,5])
a2 = np.arange(10,30)
a3 = np.eye((4))
a4 = np.identity((4))


print(a1, a2, a3, a4, sep='\n')

[1 2 3 4 5]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
print(
    a1.shape,
    a2.shape,
    a3.shape,
    a4.shape
)
print(
    a1.ndim,
    a2.ndim,
    a3.ndim,
    a4.ndim
)

(5,) (20,) (4, 4) (4, 4)
1 1 2 2


In [45]:
b1 = np.array(["Alice", "Bob", "Charlie"])
b2 = np.ones((3,4,5), dtype=np.int32)
b2

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

## 数组的运算

In [ ]:
arr = np.array([[1,2,3], [4,5,6]], dtype=np.int32)
print(
    arr * arr,
    arr ** arr,
    sep = '\n'
)
arr += arr
print(arr)

[[ 1  4  9]
 [16 25 36]]
[[    1     4    27]
 [  256  3125 46656]]
[[ 2  4  6]
 [ 8 10 12]]


array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [56]:
# 广播机制
arr1 = np.ones((3,4))
arr2 = np.ones(4)
arr3 = np.ones((1,4))
print(
    arr1,
    arr2,
    arr3,
    arr1 + arr2,
    arr1 + arr3,
    sep = '\n'
)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1.]
[[1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


In [5]:
a1 = [1,2,3,4]
a2 = [3,4]
b1 = np.arange(1, 5)    # 1,2,3,4
b2 = np.arange(1, 3)    # 1,2
print(
    a1 + a2,
    b1 + b2,
    sep = '\n'
)

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## 数组的索引

In [ ]:
arr1 = list(range(1, 10))    # 1,2,3,4,5,6,7,8,9
arr2 = np.arange(1, 10)    # 1,2,3,4,5,6,7,8,9

print(
    arr1[5:8],
    arr2[5:8],
    sep='\n'
)

[6, 7, 8]
[6 7 8]


In [11]:
# Numpy、Pandas与list类型在切片上的不同a
## 列表类型是一个浅拷贝
a = [[1], [2], [3]]
b = a[:]

print(a is b)        # False
print(a[0] is b[0])  # True

False
True


In [19]:
# 高维数组的索引
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(
    arr[0],
    arr[-1],
    arr[0:2],
    arr[:2],
    arr[0:2, 0:2],
    sep='\n'
)

[1 2 3]
[10 11 12]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]


In [27]:
# 布尔索引
arr1d = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
arr2d = np.array([["Bob", "Alice", "Charlie"], ["Linda", "Bob", "Amy"], ["Sam", "Eric", "Bob"]])
print(
    arr1d[[True, True, False, False]],
    arr2d == "Bob",
    arr2d[arr2d == "Bob"],
    arr2d[[True, True, False]],
    sep='\n'
)

[[1 2 3]
 [4 5 6]]
[[ True False False]
 [False  True False]
 [False False  True]]
['Bob' 'Bob' 'Bob']
[['Bob' 'Alice' 'Charlie']
 ['Linda' 'Bob' 'Amy']]


In [ ]:
## 对比list的查询
lst = [[1,2,3], [4,5,6], [7,8,9], [10,11,12]]
print(
    lst[1],
    lst[1:3],
    # lst[1,2],
    lst[-1],
    lst[:],
    lst[1][2],
    # lst[[1,2]],
    # lst[[True,True,False,False]],
    # lst[True,True,False,False],
    # lst > 0,
    sep='\n'
)

TypeError: '>' not supported between instances of 'list' and 'int'

In [35]:
# Fansy索引
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i
print(arr)

print(
    arr[[4,3,0,6]],
    arr[1,0],
    arr[1][0],
    sep = '\n'
)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]
1.0
1.0


In [53]:
arr = np.arange(32).reshape(8,4)
print(
    arr,
    arr[[1,5,7,2]],
    arr[:,[0,3,1,2]],
    arr[[1,5,7,2]][:,[0,3,1,2]],
    arr[[1,5,7,2]][[0,1,2,3],[0,3,1,2]],
    sep='\n'
)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[[ 0  3  1  2]
 [ 4  7  5  6]
 [ 8 11  9 10]
 [12 15 13 14]
 [16 19 17 18]
 [20 23 21 22]
 [24 27 25 26]
 [28 31 29 30]]
[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]
[ 4 23 29 10]


In [9]:
arr = np.arange(12).reshape(3,4)
print(
    arr[[0,1,2], [0,1,2]],
    arr[:,[0,1,2]],
    sep = '\n'
)

[ 0  5 10]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]


In [24]:
arr = np.arange(60).reshape(3,4,5)
b = arr[[0,1]]
b[:] = 200
print(arr,
      b,
      arr[[0,1]],
      arr[[0,1],0:2],
      sep = '\n')

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]
[[[200 200 200 200 200]
  [200 200 200 200 200]
  [200 200 200 200 200]
  [200 200 200 200 200]]

 [[200 200 200 200 200]
  [200 200 200 200 200]
  [200 200 200 200 200]
  [200 200 200 200 200]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


## 数组的代数运算

In [ ]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(
    arr,
    arr.T,
    arr.swapaxes(0,1),
    sep='\n'
)

In [4]:
print(
    arr,
    arr.T,
    np.dot(arr, arr.T),
    arr @ arr.T,
    sep='\n'
)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]
[[ 0  1  6 -1  1]
 [ 1  2  3  0  0]
 [ 0 -2  2 -1  1]]
[[ 1  2  3  0  0]
 [ 2  9  8  1 -1]
 [ 3  8 49 -8  8]
 [ 0  1 -8  2 -2]
 [ 0 -1  8 -2  2]]
[[ 1  2  3  0  0]
 [ 2  9  8  1 -1]
 [ 3  8 49 -8  8]
 [ 0  1 -8  2 -2]
 [ 0 -1  8 -2  2]]


## 数组函数

In [11]:
arr = np.arange(10)
a = np.random.rand(10)
b = np.random.rand(10)
whole, remain = np.modf(a)
print(
    # np.exp(arr),
    # a,
    # b,
    # np.maximum(a, b),
    # np.minimum(a, b),
    a,
    whole,
    remain,
    sep='\n'
)

[0.01285603 0.54265794 0.08820235 0.09667114 0.69497432 0.06768235
 0.44936118 0.47148873 0.57280013 0.78290302]
[0.01285603 0.54265794 0.08820235 0.09667114 0.69497432 0.06768235
 0.44936118 0.47148873 0.57280013 0.78290302]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
